services:
  - type: web
    name: bot-service
    runtime: python
    buildCommand: cd bot-service && pip install -r requirements.txt
    startCommand: cd bot-service && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000

  - type: web
    name: connector-service
    runtime: node
    buildCommand: cd connector-service && npm install
    startCommand: cd connector-service && npm start
    envVars:
      - key: PORT
        value: 10001
